# Generated by Django 6.0 on 2026-07-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='Blog',
        ),
    ]
