# Generated by Django 6.0 on 2026-07-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0003_rename_blogs_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
