# Generated by Django 6.0 on 2026-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0004_myblog_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
